### ISSUE TITLE
Domain Pages View

### ISSUE THREAD

**Issue by meryllblanchet** [adobe/franklin-dashboard#3]
As a dashboard user, and for each domain I am entitled to, I want to be able to:

- See and browse the list of top pages
- Know how many pages are live for the selected domain
- Configure how many pages I want to see and browse (10 - 25 - 50 - 100)
- Configure a time period for the reporting (last 30 days, last 60 days, last 90 days, since ever)
- For each domain page, see the average CWV values (LCP, FID, CLS)
- For each domain page, see the trend to previous time period if applicable: improved CWV, similar CWV, degraded CWV

**Comment by solaris007** [comment]
@trieloff - could you kindly provide specific queries / requests for the above for quick integration?

**Comment by langswei** [comment]
I am going to start some mockups and queries for the above in the style of https://mockups--franklin-dashboard--adobe.hlx.live/mockups/pageviews.html?url=www.merative.com&domainkey=blah (requires valid domainkey).  I've also put together https://mockups--franklin-dashboard--adobe.hlx.live/mockups/launcher.html for internal use which I suppose will be obsolete in the near future, replaced by a link in the sidekick which requires no user input.

If anyone needs a domainkey to view, please contact me directly.  These mockups will be static HTML pages hosted by a hlx.live URL backed by real queries.  All are welcome to contribute to the mockups, I'm just looking to add some order to the process to be more efficient in handling all these ideas from different sources and I feel this is a manageable way to do so.  Franklification can happen once the mockups and queries are in good shape.

At the moment I'm leaning toward preparation of dashboard-specific run-queries with a generally consistent format to make the results pluggable into reusable chart/list code.  Please note at this time that /pageviews.html is not using a dashboard-specific run-query and is not a model for reusability.

For the specific bullet points above:

> See and browse the list of top pages

Doable

> Know how many pages are live for the selected domain

Not doable from RUM due to sampling.  We can potentially use Fastly request data or some index-based solution not in BigQuery today.  Needs further discussion.

> Configure how many pages I want to see and browse (10 - 25 - 50 - 100)

Doable

> Configure a time period for the reporting (last 30 days, last 60 days, last 90 days, since ever)

Doable

> For each domain page, see the average CWV values (LCP, FID, CLS)

Per Slack conversation, let's target median or 75th percentile or something other than average because at times we see crazy outliers that should be omitted.

> For each domain page, see the trend to previous time period if applicable: improved CWV, similar CWV, degraded CWV

Doable

**Comment by langswei** [comment]
Dashboard deprecated, closing issue.
